language: rust
rust: nightly-2019-07-08

services:
  - docker

git:
  submodules: false

before_install:
  - travis_wait git submodule update --depth 1 --init
  - (cd rust/compiler-builtins && git submodule update --depth 1 --init libm)
  - (cd rust/rust && git submodule update --depth 1 --init src/stdsimd src/llvm-project)

install:
  - sudo apt-get install -y curl make gcc python python-crypto xz-utils
  - rustup component add rust-src
  - rustup target install aarch64-unknown-linux-gnu
  - rustup default 1.44.0 && cargo install xargo

script:
  - make optee
  - source environment
  - rustup default nightly-2019-07-08
  - (cd optee-utee && xargo build --target aarch64-unknown-optee-trustzone -vv)
  - (cd optee-teec && cargo build --target aarch64-unknown-linux-gnu -vv)
  - make examples
  - docker run --rm -it -v$(pwd):/rust-optee-trustzone-sdk -w /rust-optee-trustzone-sdk mesalocklinux/rust-optee-trustzone-sdk-qemuv8-ci bash -c "cd ci && ./ci.sh"

cache:
  timeout: 1000
  directories:
    - optee/toolchains
