language: rust
rust: nightly-2019-02-01

git:
  submodules: false

before_install:
  - travis_wait git submodule update --init
  - (cd rust/compiler-builtins && git submodule update --init libm compiler-rt)
  - (cd rust/rust && git submodule update --init src/stdsimd)

install:
  - sudo apt-get install -y curl make gcc python python-crypto xz-utils
  - rustup component add rust-src
  - rustup target install aarch64-unknown-linux-gnu
  - cargo install --git https://github.com/mssun/xargo.git --branch mssun/relative-patch-path --force

script:
  - make optee
  - source environment
  - (cd optee-utee && xargo build --target aarch64-unknown-optee-trustzone -vv)
  - (cd optee-teec && cargo build --target aarch64-unknown-linux-gnu -vv)
  - make examples

cache:
  timeout: 1000
  directories:
    - optee/toolchains
