[package]
name = "secure_storage"
version = "0.1.0"
authors = ["Mingshen Sun <mssun@mesalock-linux.org>",
           "Shengye Wan <swan@email.wm.edu>"]
edition = "2018"

[dependencies]
libc = "0.2.48"
optee_teec = { path = "../../../optee_teec" }
