[package]
name = "serde"
version = "0.1.0"
authors = ["Mingshen Sun <mssun@mesalock-linux.org>"]
edition = "2018"

[dependencies]
libc = "0.2.48"
optee-teec = { path = "../../../optee-teec" }

[build_dependencies]
uuid = { version = "0.7", features = ["v4"] }